export PYTHONPATH := "."

lint-check:
    poetry run isort . --check-only --diff
    poetry run black --check --diff .

lint-fix:
    poetry run isort . && poetry run black .

test:
    poetry run pytest tests/ -v
