FROM public.ecr.aws/lambda/python:3.11

COPY pyproject.toml poetry.lock ${LAMBDA_TASK_ROOT}/

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --only main --no-interaction --no-ansi --no-root

# Copy the serving directory contents
COPY serving/ ${LAMBDA_TASK_ROOT}/

ARG GIT_SHA
ENV GIT_SHA=${GIT_SHA}

CMD [ "app.handler" ]
