name: Serving CI

on:
  push:
    branches: [ main ]
    paths:
      - 'serving/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'serving/**'

jobs:
  ci:
    uses: ./.github/workflows/template-ci.yaml
    with:
      working-directory: serving
      ecr-repository: take-home-health-innovation-labs-serving
      dockerfile-path: serving/Dockerfile.lambda
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
