name: Training CI

on:
  push:
    branches: [ main ]
    paths:
      - 'training/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'training/**'

jobs:
  ci:
    uses: ./.github/workflows/templates/ci.yaml
    with:
      working-directory: training
      ecr-repository: take-home-health-innovation-labs-training
      dockerfile-path: training/Dockerfile
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
